spring:
  datasource:
    username: ${DB_USERNAME:mysql}
    password: ${DB_PASSWORD:password}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:quotes}
  jpa:
    hibernate:
      ddl-auto: update