name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: javalin-start

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Restore Gradle caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Save the Javalin-Start artifact
        uses: actions/upload-artifact@v1
        with:
          name: javalin-artifact
          path: ./javalin/javalin-start/build/libs

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code back, it contains the Dockerfile
        uses: actions/checkout@v2

      - name: Restore Javalin-Start artifact from storage
        uses: actions/download-artifact@v1
        with:
          name: javalin-artifact

      - name: Build a Docker Image
        run: |
          docker build \
            --file ./javalin/javalin-start/Dockerfile \
            --tag image \
            ./javalin-artifact

      - name: Login into the Docker Repository
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Determine the version
          VERSION=latest

          # Small debug prints
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          # Push it
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION